### ISSUE TITLE
Main thread - documentation vs wrapping fns in modules

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#461]
**System Information**

* Pythonista 3.1.1 (311015), Default interpreter 3.6.1
* iOS 11.0.3, model iPad, resolution (portrait) 2048.0 x 2732.0 @ 2.0

**Description**

I think that we shouldn't expect that users have knowledge about `UIKit`, main thread, ... Also it's unclear to some iOS devs what must and what must not be called on the main thread. `UIKit` documentation says, that any UI manipulation must be done on the main thread.

But here's an example - `clipboard` module. We both know it's `UIPasteboard`, but how is some common user supposed to know this? Try to run attached code. First time - works. Second time - Pythonista freezes. And here we have another bug report about freezed Pythonista. Adding `@on_main_thread` fixes this issues and you call it as many times as you want.

Also it's unclear to me what's the Pythonista approach. Shouldn't be all fns in internal modules wrapped with `@on_main_thread`? User is responsible for this? Can we help them by doing this in internal modules? Is there performance penalty by doing this? Or should we enhance documentation somehow? Should be user responsible for this in the `ui` module only and every other module should contain fns wrapped with `@on_main_thread` where necessary? How user can differentiate between `UIKit` and other frameworks when we have `clipboard`, `contacts`, `ui` for example. What is the target audience of Pythonista? Someone like me who knows how it works? Common user who just want to write some scripts? Is `UIKit` knowledge required to work with Pythonista?

Can you shed some light on this @omz? Just to know if things like this one should be reported as `bug` (missing `@on_main_thread`) or as `enhancement` (update docs). Sometimes I see over simplification of `UIKit` classes / functions (why not), sometimes user has to swim in unknown waters ... I'm just trying to understand in which direction is Pythonista going (or should go). Thanks.

**Sample code**

```python
#!python3

import clipboard

print('1')
clipboard.set('Hallo')
print('2')
```

**Comment by omz** [comment]
`on_main_thread` is only intended for `objc_util`, other modules should handle this internally, and if it isn't handled properly, I consider that a bug.

I'll have to check, but I don't think the `clipboard` module currently dispatches to the main thread because I didn't think that was necessary. If it is, my bad, and I should fix it – I definitely don't expect users of the `clipboard` module to know (or care) about the UIKit main thread.

**Comment by zrzka** [comment]
@omz thanks for the heads up. Did update title & content of the initial comment & added label `bug`.

**Comment by zrzka** [comment]
Note to self - remove `@on_main_thread` from `sysinfo.py` (this repo) when this one will be fixed.

**Comment by omz** [comment]
I've just looked at this, and `clipboard.set()` actually calls `setString:` (`UIPasteboard`) on the main thread already. I also can't reproduce the freezing issue at all, with or without `on_main_thread`. Is this the actual code you were using, or was it perhaps part of a more complex setup?

**Comment by zrzka** [comment]
@omz tested this in 311016 and it still freezes. But now it freezes when I run this script 3rd time for example. The number is varying. My bad is that I forgot to mention that I run this script with `Cmd R`. When I try to run this script by tapping on the play button, I can run it ten times in a row without any issues. Weird one. Will try to trash Pythonista, documents, everything and will check again with clean installation.

**Comment by zrzka** [comment]
P.S. Yes, the sample code is minimal example which allows me to reproduce it. I found it when I was copying BM installation command to the clipboard during Pythonista startup.

**Comment by zrzka** [comment]
Tried again (BM, everything, ... disabled).

**Working script**

* `Cmd R` or play button, works

```python
#!python3

import clipboard
from objc_util import on_main_thread

@on_main_thread
def clipboard_set():
    clipboard.set('Hallo')

print('1')
clipboard_set()
print('2')
```

**Freezing script**

* Play button works
* `Cmd R` freezes, not crashes, UI is not responsive, stop button not responding, several minutes, than I forced quit it, kind of random freeze, sometimes two runs, sometimes three, ...

```python
#!python3

import clipboard

def clipboard_set():
    clipboard.set('Hallo')

print('1')
clipboard_set()
print('2')
```

Checked logs ...

```
Nov 13 09:26:04 Robert-Vojtas-iPad SpringBoard(KeyboardArbiter)[56] <Error>: [<_UIKeyboardArbiterHandle: 0x1c810c4e0; PID 648: com.omz-software.Pythonista3 <(null)>; hosting PIDs {(
)}; level 3.000000; active NO [wants NO]; suppression 0>] timed out with 1 assertions remaining, disconnecting
Nov 13 09:26:04 Robert-Vojtas-iPad SpringBoard(KeyboardArbiter)[56] <Error>: -[_UIKeyboardArbiter runOperations:onHandler:]_block_invoke Failed to access <_UIKeyboardArbiterHandle: 0x1c810c4e0; PID 648: com.omz-software.Pythonista3 <(null)>; hosting PIDs {(
)}; level 3.000000; active NO [wants NO]; suppression 0> remote service: Error Domain=NSCocoaErrorDomain Code=4099 "The connection from pid 648 was invalidated from this process." UserInfo={NSDebugDescription=The connection from pid 648 was invalidated from this process.}
Nov 13 09:26:04 Robert-Vojtas-iPad SpringBoard(FrontBoard)[56] <Error>: [com.omz-software.Pythonista3] Provision violated for watchdog process-exit: <FBSProcessResourceProvision: 0x1c82f2c80; allowance: <; FBSProcessResourceAllowance; type: realTime; timeValue: 5.0s>; violated: YES>
Nov 13 09:26:04 Robert-Vojtas-iPad SpringBoard(FrontBoard)[56] <Notice>: [com.omz-software.Pythonista3] Executing termination for reason user initiated quit with request: <FBSProcessTerminationRequest: 0x1c9860680; label: watchdog provision violated; exceptionCode: Watchdog Violation (0x8BADF00D); reportType: CrashLog; explanation: "process-exit watchdog transgression: com.omz-software.Pythonista3 exhausted real (wall clock) time allowance of 5.00 seconds">
```

... so, it seems that it has nothing to do with the clipboard itself, but it's kinda keyboard related. Anyway even these messages aren't clear to me. Tried to google, nothing interesting found. Will try to find more. What's weird is that `@on_main_thread` _fixes_ this issue. Weird ...
